name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests for default features
      run: cargo test --verbose
    - name: Run tests for no features
      run: cargo test --verbose --no-default-features
    - name: Run tests for all features
      run: cargo test --verbose --all-features
      
